openapi: 3.0.3
info:
  title: Toolbox API Challenge
  description: API que expone información procesada desde archivos CSV provenientes de un servicio externo.
  version: 1.0.0
  contact:
    name: "Cesar Daniel Pineda"
    url: "https://github.com/cpineda1985/api-challenge/blob/main/swagger.yaml"
    email: cesardaniel.pineda@gmail.com
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

paths:
  /files/data:
    get:
      summary: Obtener archivos procesados
      description: Devuelve una lista de archivos con sus líneas válidas. Permite filtrar por nombre de archivo fileName, incluir líneas parcialmente válidas includeEmpty y aplicar paginación limit y offset
      parameters:
        - name: fileName
          in: query
          required: false
          description: Nombre del archivo CSV a filtrar. Si no se especifica, se devuelven todos los archivos válidos.
          schema:
            type: string
            example: test2.csv

        - name: includeEmpty
          in: query
          required: false
          description: Incluir líneas vacías o con campos parcialmente válidos (campos nulos). Si se omite, solo se devuelven líneas 100% válidas.
          schema:
            type: boolean
            example: true

        - name: limit
          in: query
          required: false
          description: Número máximo de archivos a devolver (aplica solo si no se usa fileName).
          schema:
            type: integer
            example: 3

        - name: offset
          in: query
          required: false
          description: Posición inicial desde donde devolver archivos (aplica solo si no se usa fileName).
          schema:
            type: integer
            example: 0

      responses:
        '200':
          description: Datos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    file:
                      type: string
                      example: test2.csv
                    lines:
                      type: array
                      items:
                        type: object
                        properties:
                          text:
                            type: string
                            nullable: true
                            example: HrOURzXOfQBNsmYFcKWvRnEhxNDUZr
                          number:
                            type: integer
                            nullable: true
                            example: 874512
                          hex:
                            type: string
                            nullable: true
                            example: 79d6ae2f40ae06db9cefe7ebf173664a
              examples:
                ejemploPaginado:
                  summary: Ejemplo con paginación
                  value:
                    - file: test1.csv
                      lines:
                        - text: "abc"
                          number: 123
                          hex: "abcdef123456abcdef123456abcdef12"
                    - file: test2.csv
                      lines: []

        '404':
          description: Archivo no encontrado o sin líneas válidas (cuando `fileName` es provisto y no hay resultados)
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  details:
                    type: string
                    nullable: true
                  status:
                    type: integer
              example:
                code: SYS-ERR
                message: Not Found
                details: null
                status: 404

        '500':
          description: Error interno al procesar archivos o conectarse al API externo
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  details:
                    type: string
                    nullable: true
                  status:
                    type: integer
              example:
                code: SYS-ERR
                message: Internal Server Error
                details: "Error en red o parseo"
                status: 500

  /files/list:
    get:
      summary: Obtener lista de archivos disponibles
      description: Devuelve el listado de archivos proporcionado directamente por el API externo. Permite filtrar por nombre de archivo si se proporciona `fileName`.
      parameters:
        - name: fileName
          in: query
          required: false
          description: Nombre del archivo CSV a buscar en la lista. Si no se especifica, se devuelven todos.
          schema:
            type: string
            example: test3.csv
      responses:
        '200':
          description: Lista de archivos obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string
                      example: test1.csv
              examples:
                ejemploListaArchivos:
                  summary: Ejemplo de lista completa
                  value:
                    files:
                      - test1.csv
                      - test2.csv
                      - test3.csv
                      - test18.csv
                      - test4.csv
                      - test5.csv
                      - test6.csv
                      - test9.csv
                      - test15.csv
        '404':
          description: Archivo no encontrado en la lista
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  details:
                    type: string
                    nullable: true
                  status:
                    type: integer
              example:
                code: SYS-ERR
                message: Not Found
                details: null
                status: 404

        '500':
          description: Error al obtener la lista desde el API externo
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  details:
                    type: string
                    nullable: true
                  status:
                    type: integer
              example:
                code: SYS-ERR
                message: Internal Server Error
                details: Error de red o token inválido
                status: 500